version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: chess-backend
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/chess-backend

volumes:
  db-data:
